### ISSUE TITLE
Nested csonschema

### ISSUE THREAD

**Issue by nemoeslovo** [cybertk/csonschema#8]
It would be cool if it is possible to create csonschema with dependency on another one.
Example:

```
image.csonschema:
```

```
$defs:
    image:
        w: 'integer'
        h: 'integer'
        url: 'string'
small: 'image'
medium: 'image'
large: 'image'
```

```
user.csonschema:
```

```
$defs:
   imageModel:
      $include: 'image.csonschema'
   avatar: 'imageModel'
```
